version: '2'
services:
  customer:
    image: "sureshkanna/customer:0.20.0"
    ports:
     - "2017:8080"    
    networks:
      - kanna-network
  order:
    image: "sureshkanna/order:0.20.0"
    networks:
      - kanna-network
networks:
  kanna-network:
    driver: bridge  
